esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    pin: GPIO4
    id: relay
    name: "${friendly_name}"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: button
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - switch.toggle: relay
